In [1]:
import pandas as pd

In [ ]:
%pip install -r requirement.txt

Collecting pandas (from -r requirement.txt (line 2))
  Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy (from -r requirement.txt (line 3))
  Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib (from -r requirement.txt (line 6))
  Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting seaborn (from -r requirement.txt (line 7))
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn (from -r requirement.txt (line 10))
  Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting scipy (from -r requirement.txt (line 11))
  Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\Learning Course HK2 năm 2\Trí tuệ nhân tạo\Anime recommender system\venv\Lib\site-packages (from pandas->-r requirement.txt (line 2)) (2.9.0.post0)
Collecting tzdata (from pandas->-r requirement.txt (line 2))
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirement.txt (line 6))
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirement.txt (line 6))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->-r requirement.txt (line 6))
  Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->-r requirement.txt (line 6))
  Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in E:\Learning Course HK2 năm 2\Trí tuệ nhân tạo\Anime recommender system\venv\Lib\site-packages (from matplotlib->-r requirement.txt (line 6)) (26.2)
Collecting pillow>=8 (from matplotlib->-r requirement.txt (line 6))
  Using cached pillow-12.2.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib->-r requirement.txt (line 6))
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting joblib>=1.3.0 (from scikit-learn->-r requirement.txt (line 10))
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn->-r requirement.txt (line 10))
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in E:\Learning Course HK2 năm 2\Trí tuệ nhân tạo\Anime recommender system\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirement.txt (line 2)) (1.17.0)
Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.2 MB 2.2 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.2 MB 2.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.2 MB 2.8 MB/s eta 0:00:03
   ------------ --------------------------- 2.6/8.2 MB 2.8 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.2 MB 2.7 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.2 MB 2.7 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.2 MB 2.5 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.2 MB 2.2 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.2 MB 2.0 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.2 MB 2.0 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 1.9 MB/s eta 0:00:02
   ---------------------- ----------------- 4.7/8.2 MB 1.7 MB/s eta 0:00:02
   ---------------------- ----------------- 4.7/8.2 MB 1.7 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.2 MB 1.6 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.2 MB 1.6 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.2 MB 1.5 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.2 MB 1.5 MB/s eta 0:00:02
   -------------------------- ------------- 5.5/8.2 MB 1.4 MB/s eta 0:00:02
   -------------------------- ------------- 5.5/8.2 MB 1.4 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.2 MB 1.3 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.2 MB 1.3 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.2 MB 1.3 MB/s eta 0:00:02
   ------------------------------ --------- 6.3/8.2 MB 1.2 MB/s eta 0:00:02
   ------------------------------ --------- 6.3/8.2 MB 1.2 MB/s eta 0:00:02
   ------------------------------- -------- 6.6/8.2 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.2 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.2 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.2 MB 1.1 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 1.1 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.1 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.1 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 993.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 993.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 993.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 993.0 kB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 899.5 kB/s  0:00:09
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Using cached pillow-12.2.0-cp312-cp312-win_amd64.whl (7.1 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib, seaborn

   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   -- -------------------------------------  1/15 [threadpoolctl]
   ----- ----------------------------------  2/15 [pyparsing]
   ----- ----------------------------------  2/15 [pyparsing]
   ----- ----------------------------------  2/15 [pyparsing]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ------------- --------------------------  5/15 [kiwisolver]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   --------------------- ------------------  8/15 [cycler]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]

In [3]:
from pathlib import Path
import pandas as pd

anime_path = Path("anime data") / "anime.csv"
anime = pd.read_csv(anime_path)
anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [5]:
rating_path = Path("anime data") / 'rating.csv'
rating = pd.read_csv(rating_path)

In [6]:
rating.describe()

            user_id      anime_id        rating
count  7.813737e+06  7.813737e+06  7.813737e+06
mean   3.672796e+04  8.909072e+03  6.144030e+00
std    2.099795e+04  8.883950e+03  3.727800e+00
min    1.000000e+00  1.000000e+00 -1.000000e+00
25%    1.897400e+04  1.240000e+03  6.000000e+00
50%    3.679100e+04  6.213000e+03  7.000000e+00
75%    5.475700e+04  1.409300e+04  9.000000e+00
max    7.351600e+04  3.451900e+04  1.000000e+01